# Generated by Django 4.0.10 on 2024-03-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mswm', '0001_initial'),
        ('accounts', '0002_alter_permission_description_alter_role_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='mswm.mswmsite'),
        ),
    ]
