# Generated by Django 4.0.10 on 2024-03-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSWMSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_number', models.IntegerField(null=True)),
                ('site_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.FloatField(null=True)),
                ('fuel_cost_km_loaded', models.FloatField(null=True)),
                ('fuel_cost_km_empty', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('fuel_level', models.FloatField(null=True)),
                ('current_load', models.FloatField(null=True)),
                ('landfill_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landfill_site', to='mswm.mswmsite')),
                ('sts_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sts_site', to='mswm.mswmsite')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mswm.vehicletype')),
            ],
        ),
    ]
