# Generated by Django 4.0.10 on 2024-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mswm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mswmsite',
            name='site_type',
            field=models.CharField(choices=[('STS', 'Solid Waste Transfer Station'), ('Landfill', 'Landfill'), ('Other', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='capacity',
            field=models.FloatField(choices=[(3, '3 Tonnes'), (5, '5 Tonnes'), (10, '7 Tonnes'), (15, '15 Tonnes')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('Open Truck', 'Open Truck'), ('Dump Truck', 'Dump Truck'), ('Compactor', 'Compactor'), ('Container Career', 'Container Career'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
