# Generated by Django 4.0.10 on 2024-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mswm', '0004_travellogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mswmsite',
            name='current_load',
            field=models.FloatField(null=True),
        ),
    ]
