# Pull Base Image
FROM python:3.10.4-alpine

# Set Environment Variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1 
ENV PYTHONUNBUFFERED 1

# Set the work directory
WORKDIR /app/backend

# Install Dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy Project
COPY . .

